[workspace]

members = [
    "thepipelinetool_core",
    "thepipelinetool_runner",
    "thepipelinetool_utils",
    "thepipelinetool_task",
    "thepipelinetool_proc_macro",
    "thepipelinetool",
    "thepipelinetool_operators",
    "thepipelinetool_server",
    "examples",
]
resolver = "2"