services:
  tpt-server:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - 8000:8000
    environment:
      - REDIS_URL=redis://cache:6379
  tpt-worker:
    build:
      context: .
      dockerfile: worker.Dockerfile
    # deploy:
    #   mode: replicated
    #   replicas: 2
    volumes:
      - ./bin/:/worker/bin/
      # - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    privileged: true
    environment:
      - REDIS_URL=redis://cache:6379
      - EXECUTOR="Docker"
  cache:
      container_name: cache
      image: redis
      restart: always
      ports:
        - 6379:6379
      command: redis-server --save 60 1 --loglevel warning