[package]
name = "thepipelinetool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.31", features = [ "serde" ] }
serde_json = "1.0"
task = { path = "../task" }
utils = { path = "../utils" }
#graph = { path = "../graph" }
runner = { path = "../runner" }
serde = "1.0.189"
proc_macro = { path = "../proc_macro" }
clap = { version = "4.4.7", features = [ "cargo" ] }
saffron = { git = "https://github.com/cloudflare/saffron.git" }
parking_lot = "0.12.1"

[dev-dependencies]
rand = "0.8"