[package]
name = "thepipelinetool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
serde_json = "1.0"
task = { path = "../task" }
utils = { path = "../utils" }
runner = { path = "../runner" }
serde = "1.0.189"
clap = { version = "4.4.7", features = [ "cargo" ] }

[dev-dependencies]
rand = "0.8"