[package]
name = "runner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
task = { path = "../task" }
serde_json = "1.0"
chrono = "0.4.31"
utils = { path = "../utils" }