name: CI

on:
  push:
    branches:
      - '**'
    paths:
      - .github/workflows/ci.yml
      - examples/**
      - thepipelinetool/**
      - thepipelinetool_core/**
      - thepipelinetool_operators/**
      - thepipelinetool_proc_macro/**
      - thepipelinetool_runner/**
      - thepipelinetool_server/**
      - thepipelinetool_task/**
      - thepipelinetool_utils/**
      - Cargo.toml
      - scripts/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build -p thepipelinetool --release
      - run: ./scripts/build_examples.sh
      - run: ./scripts/run_release.sh  