name: examples

on:
  push:
    branches:
      - '**'
    paths:
      - .github/workflows/examples.yml
      - runner/**
      - task/**
      - thepipelinetool/**
      - utils/**
      - Cargo.toml
jobs:
  examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/
            target/
          key: ${{ runner.os }}-cargo-runner-${{ hashFiles('runner/Cargo.toml') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build          